version: "3.8"

services:
  pohuang-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pohuang-ai-website
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge
